Repository natura-cosmeticos/natds-js, pull requests merged in 2019-12, with the labels that each got.

#167 fix(publish): fixes publishing folder by fixing it in the package.json
  packages/mobile/package.json
  packages/styles/package.json
  packages/web/package.json
  scripts/bump-production-version.sh
Labels: bug

#164 Feature/add web typography component prop
  packages/docs/src/web/Typography/Typography.mdx
  packages/web/.jest-test-results.json
  packages/web/src/Components/Typography.tsx
Labels: enhancement

#173 fix(web): fixing TextField label for when is empty and with required
  packages/web/src/Components/TextField/index.tsx
  packages/web/src/__tests__/TextField.spec.tsx
  packages/web/src/__tests__/__snapshots__/TextField.spec.tsx.snap
  scripts/bump-production-version.sh
Labels: bug

#176 docs(docs): changed fabs knobs to comply with UX
  packages/docs/src/web/Fab/Fab.docs.mdx
  packages/docs/src/web/Fab/Fab.story.tsx
  packages/docs/src/web/Fab/sections.tsx
Labels: documentation

#177 chore(ci): added testing result generation to CI and removed it from files
  .travis.yml
  package.json
  packages/icons/package.json
  packages/mobile/package.json
  packages/styles/package.json
  packages/web/package.json
  scripts/build-pre-release.sh
  scripts/build-release.sh
Labels: enhancement
